### ISSUE TITLE
请问是否能够提供rss订阅

### ISSUE THREAD

**Issue by Yisaer** [Xiaomi-Info/xiaomi-info.github.io#1]
非常感谢你博客中对istio的源码解析，请问是否还会持续更新？ 如果持续更新的话，能否添加RSS订阅方式？

**Comment by Newt0n** [comment]
可以 Star 和 Watch 项目，有更新的时候会有邮件提醒，下次更新的时候我们加上 rss 插件，感谢关注✌️

**Comment by ipfans** [comment]
这次更新还是没加上🤦‍♂️

**Comment by Newt0n** [comment]
已生成 RSS feed：
https://xiaomi-info.github.io/atom
