### ISSUE TITLE
RSS Feed 中的文章链接域名错误

### ISSUE THREAD

**Issue by yhyy135** [Xiaomi-Info/xiaomi-info.github.io#3]
[RSS Feed](https://xiaomi-info.github.io/atom) 中的文章链接域名为 xiaomi-info.github.com 而非 xiaomi-info.github.io

该错误导致无法正常访问博文页面，可能是 Hexo 配置文件中域名配置错误，望修复。

非常感谢贵团队能够分享相关技术文章，受益良多。

**Comment by Albert-Zuo** [comment]
+1 RSS Feed 中的文章链接域名为 xiaomi-info.github.com 而非 xiaomi-info.github.io
2021年5月21了还没有改。。。。

**Comment by Albert-Zuo** [comment]
为什么我觉得还是得把RSS的改成 xiaomi-info.github.io 才行，不然图片无法加载

**Comment by Newt0n** [comment]
收到，稍后修复一次，感谢反馈🙏🏽

**Comment by Newt0n** [comment]
看看是否修复了？感谢反馈。

**Comment by Albert-Zuo** [comment]
> 看看是否修复了？感谢反馈。

已经修复完成，RSS的目前体验十分完美，感谢你的辛勤劳动，希望后续可以拜读贵部门更多精品之作
