### ISSUE TITLE
RSS 文件的网址与实际网址不统一

### ISSUE THREAD

**Issue by Albert-Zuo** [Xiaomi-Info/xiaomi-info.github.io#4]
RSS订阅文件声明的网址为 https://xiaomi-info.github.com  ，但是实际访问路径是  https://xiaomi-info.github.io   ，两者不统一，对于RSS阅读十分不友好，基本访问不了图片，也无法直接浏览网站

**Comment by Newt0n** [comment]
看看是否修复了？感谢反馈。

**Comment by Albert-Zuo** [comment]
> 看看是否修复了？感谢反馈。

已经修复完成，RSS的目前体验十分完美，感谢你的辛勤劳动，希望后续可以拜读贵部门更多精品之作
